# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

r:
  - devel
  - release
  - oldrel
  - 3.5
  - 3.4
  - 3.3

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
